### ISSUE TITLE
Unnecessary comma causing error during code compression

### ISSUE THREAD

**Issue by mrtimw** [leemotive/decimal-format#8]
Hi! 
      
Firstly, thanks for your work on this project!

Today I used [patch-package](https://github.com/ds300/patch-package) to patch `decimal-format@2.0.2` for the project I'm working on.

The build of my Angular 7 project was failing due to an error coming from [Terser](https://github.com/terser/terser):

```
ERROR in main.2f0fccaae32e165b8a32.js from Terser
Unexpected token: punc ()) [node_modules/decimal-format/es/index.js:207,0]
```

The cause is an unnecessary comma.

Here is the diff that solved my problem:

```diff
diff --git a/node_modules/decimal-format/es/index.js b/node_modules/decimal-format/es/index.js
index 149f74f..dc701f9 100644
--- a/node_modules/decimal-format/es/index.js
+++ b/node_modules/decimal-format/es/index.js
@@ -203,7 +203,7 @@ function round(n, scale, roundingMode) {
         return n;
       } else {
         throw Error(
-          'ArithmeticException: Rounding needed with the rounding mode being set to RoundingMode.UNNECESSARY',
+          'ArithmeticException: Rounding needed with the rounding mode being set to RoundingMode.UNNECESSARY'
         );
       }
     }
diff --git a/node_modules/decimal-format/lib/index.js b/node_modules/decimal-format/lib/index.js
index 234c5f5..d297017 100644
--- a/node_modules/decimal-format/lib/index.js
+++ b/node_modules/decimal-format/lib/index.js
@@ -207,7 +207,7 @@ function round(n, scale, roundingMode) {
         return n;
       } else {
         throw Error(
-          'ArithmeticException: Rounding needed with the rounding mode being set to RoundingMode.UNNECESSARY',
+          'ArithmeticException: Rounding needed with the rounding mode being set to RoundingMode.UNNECESSARY'
         );
       }
     }
```

Please could you make this change in the source?

<em>This issue body was [partially generated by patch-package](https://github.com/ds300/patch-package/issues/296).</em>

**Comment by leemotive** [comment]
@mrtimw Thanks for work! The comma is appended by [prettier](https://prettier.io/) 。The `trailingComma` option was configured as [`all`](https://prettier.io/docs/en/options.html#trailing-commas).

> "all" - Trailing commas wherever possible (including function parameters and calls). To run, JavaScript code formatted this way needs an engine that supports ES2017 (Node.js 8+ or a modern browser) or downlevel compilation. This also enables trailing commas in type parameters in TypeScript (supported since TypeScript 2.7 released in January 2018).

I tried terser with the following command
```bash
$ terser index.js --compress --mangle
```
It works fine and no exception reported.

So is it possible to solve your question by 
- change your webpack or babel configuration
- upgrade the version of related dependencies
- use decimal/dist/decimalFormat.min.js which is compressed use umd

**Comment by mrtimw** [comment]
@leemotive Thanks for your reply

I'm not able to change the webpack/babel configuration on this project so instead have used decimal/dist/decimalFormat.min.js. 

This has resolved my issue. Thanks again!
